# à¹„à¸Ÿà¸¥à¹Œ _config.yml
title: "ğŸŒ¸ My Space"
description: "Welcome to my GitHub page! ğŸ˜‹âœŒğŸ» "
remote_theme: pages-themes/cayman@v0.2.0

# à¸›à¸£à¸±à¸šà¹à¸•à¹ˆà¸‡à¸˜à¸µà¸¡
plugins:
  - jekyll-remote-theme

# à¹€à¸à¸´à¹ˆà¸¡ custom CSS
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
